spring:
  datasource:
    url: jdbc:oracle:thin:@//10.10.130.220:1521/dg1omdb12c
    username: SCM
    password: DFDRES#23
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect